- .npmignore
- .travis.yml
- package.json
Added `.travis.yml` configuration file and public flag to `package.json`.
> Travis CI integration

- .travis.yml
- package.json
Added coverall script to `travis.yml` to calculate coverage percentage in builds.
> Added coverall to travis.yml

- README.md
- Manipulate data
- Custom Elements
- React Select
- React Datepicker
> Add more examples on documentation

- README.md
Hey, I'm updating the first look of README and adding some details about our guidelines, giving some introduction about the Code of Conduct and contributing guide 😄
> Update README's first look and adds some details about our guidelines

- lib/components/Select.tsx
This PR fix issue #11, when a `<Select />` has an initial value.
> Fix initial set value in select

- README.md
Add missing links on the badges.
> docs: Fix badges link [skip ci]

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/documentation-report.md
- .github/ISSUE_TEMPLATE/enhancement-request.md
Issue templates needed a little tweaks to become more consistency between itself. This change fix this.
> chore: Update issue templates to improve consistency

- .github/PULL_REQUEST_TEMPLATE
* This PR adds a PULL_REQUEST_TEMPLATE just to make future PRs description more organised and consistent, also making the PR information easier to find.
Please feel free to add any suggestions/changes! :D
> feat: Add pull request template

- README.md
Remove Textarea mention from README.md
The Textarea component was removed, but the README still mentioned the component in the `Basics` section.
> docs: Remove Textarea mention from README.md

- README.md
Makes README follow the ajusts regarding coding style that PR #71 brought.
> docs: Fix readme "style"

- .github/CONTRIBUTING.md
Change `this` to `these` in ToC.
> docs: Fix typo in ToC

- package.json
It's necessary to run `git add` after `lint-staged`, otherwise the changes made aren't committed.
Completes the work done in #84.
> chore: Commit files after lint-staged changes

- README.md
Add an observation that, when  your define a schema to `Form` you'll need to write each field explicitly, even if some field is not required.
Let's suppose I want to submit my email and name to receive spams. 
```js
import React from 'react';
import { Form, Input } from '@rocketseat/unform';
import * as Yup from 'yup';
const schema = Yup.object().shape({
email: Yup.string()
.email('Custom invalid email message')
.required('Custom required message'),
});
function App() {
function handleSubmit(data) {
// data: { email: 'higo@rockeseat.com.br' }
}
return (
<Form schema={schema} onSubmit={handleSubmit}>
<Input name="email" />
<Input name="name" />
<button type="submit">Submit</button>
</Form>
);
}
```
Did you notice that only `email` field was …
> docs: Additional documentation on how the schema works

- .travis.yml
Adds automatic build and publish to gh-pages with Travis CI
Adds Travis CI for docs and publish to gh-pages.
None.
> ci: Add gh-pages for docs

- docs/website/siteConfig.js
Fixes docs page.
Fixes docs page URL and assets.
None.
> docs: Fix gh-pages

- docs/website/siteConfig.js
Adds a currently missing a slash on baseUrl.
A bar was missing at the end of the baseUrl.
None.
> docs: Add slash on baseUrl

- README.md
A simple description that explains the structure needed to add the options list to the select element.
> docs: Add description to select element section

- README.md
Add back buttons to make the navigation on docs easier.
> docs: Add back buttons

- README.md
- package.json
**Changes in 1.6.0**
- Minor changes on documentation #121 #132
- Add check and choice component #110
- Allow setting data on `resetForm` #114 
- Small improvements on tests #120
> feat: Release unform 1.6.0 🎉

- package.json
This PR adds a `prepublish` script to `package.json` 🎉
> chore: Add prepublish script to package.json

- .travis.yml
Remove docs building at `travis` config.
(Should have been removed in #142)
> ci: Remove docs build

- docs/src/docs/guides/validation.mdx
Removing previus errors on submit
I've made small changes on some examples. 
Like `formRef.current.setErrors({})` to clean the previus errors.
> docs: Add missing async and fixing example

- docs/src/@rocketseat/gatsby-theme-docs/text/index.mdx
This pull request corrects the package's name for react native.
> docs: corrects react native package

- docs/src/docs/faq.mdx
- docs/src/docs/migration-guide.mdx
- docs/src/docs/recipes/styled-components.mdx
- Minor typo fixes in FAQ, Migration Guide and Styled Component sections
Fixes #181
> docs: Fix typos in faq, migration and styled-component guides

- docs/src/docs/guides/get-set-field-error.mdx
- docs/src/docs/guides/reset-form.mdx
- docs/src/docs/recipes/simple-input.mdx
- docs/src/docs/recipes/typescript.mdx
Fixed some typos in the documentation.
Fixes #180 
> docs: Fix typos errors

- docs/src/docs/recipes/simple-input.mdx
> docs: Added useEffect import in simple input live example

- docs/src/docs/recipes/simple-input.mdx
On registerField, the path was `target.value`, but the correct is only `value`
> docs: Fix Simple Input Example

- docs/gatsby-config.js
- docs/package.json
- docs/src/docs/migration-guide.mdx
- docs/yarn.lock
Update [`@rocketseat/gatsby-theme-docs`](https://github.com/Rocketseat/gatsby-themes/tree/master/%40rocketseat/gatsby-theme-docs) to latest version, that includes a table of contents, edit page on GitHub link and fixes an issue with prev/next links.
> chore(docs): Update gatsby-theme-docs to 2.1.0

- README.md
só arrumando uns errinhos de inglês pra ficar melhor de ler :)
> docs: Fix minor english errors

- docs/config/sidebar.yml
- docs/src/docs/examples/react-native-input-mask.mdx
Add example of input mask using react native
Repository at: [unform-rn-mask](https://github.com/harlancleiton/unform-rn-mask)
> docs: Add react native input mask example

- docs/src/docs/examples/react-select.mdx
Remove path property in the registerField function
And refactor getValue function.
> docs: Fix React Select Examples

- docs/src/docs/examples/checkbox.mdx
Create the .mdx file to example how to use checkbox
input with Unform
> docs: Add checkbox input example

- docs/package.json
- docs/yarn.lock
Fixes #227 updating [@rocketseat/gatsby-theme-docs](https://github.com/Rocketseat/gatsby-themes/tree/master/%40rocketseat/gatsby-theme-docs) to the latest version :tada:
> fix(docs): Links inside documentation #227

- .eslintrc.js
remove unused import in .eslintrc
> chore: remove unused import in .eslintrc

- .github/CONTRIBUTING.md
- .github/PULL_REQUEST_TEMPLATE
- LICENSE
- README.md
- docs/LICENSE
- docs/config/sidebar.yml
- docs/gatsby-config.js
- packages/core/package.json
- packages/mobile/package.json
- packages/web/package.json
In this PR we have updated the license year to 2021 and also update all repository URLs to point to the new org. 
Also fixed some label links on the guidelines.
Resolves OSS-17
> chore: prepare to move the repository to the own org

- .github/workflows/test.yml
- README.md
This PR fixes an error on the Coveralls badge.
**Additional context** 
Resolves OSS-22
> ci: Create coveralls workflow

- .github/CONTRIBUTING.md
- .github/PULL_REQUEST_TEMPLATE
- README.md
- docs/gatsby-config.js
Rename occurrences of `master` to `main`.
n/a
> chore: Rename master to main

- lerna.json
- package.json
Adds scripts for publishing packages.
> chore: Add publish scripts
