unform/unform

lib/Form.tsx
Now it throws an error in case the validation process encounters a problem.
This improves debugging an error when using `yup`.
=> Throw error from yup

.travis.yml
Travis was running builds even when only documentation files were edited.
Now Travis won't run if you have only edited files under these circumstances:
- Markdown files;
- Files inside example folder;
- Files inside docs folder;
Based on: https://github.com/facebook/react/pull/2000
=> Skip Travis builds in documentation changes

README.md
Update `Table of contents` to match `Contributing` section header and also add the missing section `License`.
In the `Contributing` section, replace the old steps to contribute with an intro and a link to our Contributing Guide.
=> Update TOC and `Contributing` section in README

README.md
`onChange` function is now being passed as an arrow function to prevent warnings.
This was done based on #13.
=> Update react-select and react-datepicker examples

.travis.yml
Travis was skipping builds in PR's when a single commit changes only docs or markdowns.
For now i think the better for us is to add [skip ci] in commit message then Travis will skip it.
=> Remove skip rule from Travis

.eslintrc.js, .travis.yml, README.md, __tests__/Form.spec.tsx, __tests__/components/Select.spec.tsx, __tests__/utils/CustomInputClear.tsx, __tests__/utils/CustomInputParse.tsx, example/package.json, example/src/App.tsx, example/src/components/DatePicker.tsx, example/src/components/ReactSelect.tsx, example/yarn.lock, jest.config.js, lib/Form.tsx, lib/components/Input.tsx, lib/components/Select.tsx, lib/components/Textarea.tsx, lib/types.ts, lib/useField.ts, package.json, yarn.lock
In some cases Unform was duplicating fields references as registerField was beign called from ref prop and every re-render was causing a new register.
Also, field references were being saved to a simple variable inside Form, and now they are saved to state so we can easily manipulate and reuse this information with the power of React reconciler.
---
`registerField` function now includes new two parameters:
- `parseValue`: Function that receives captured value from element reference and return the mutated value;
- `clearValue`: Function that clears the element data, if setted will override the default clear format from Unform;
---
Select element now can't be multiple, so for multiple selects we should use react-select.
---
`getValue `doesn't exist anymore in registerField. All the form …
=> New registerField strategy and reset form

.github/CONTRIBUTING.md, .travis.yml, commitlint.config.js, package.json, yarn.lock
Create a commit convention for our organization, install `commitlint` and configure it as a hook to lint commit message. This helps will your team and contribuitors to adhering to the said commit convention.
Add a `commitlint` script in Travis to catch anyone that tries to bypass the local validation.
Update `CONTRIBUTING.md` to reflect the convention created by this commit.
Closes #23
=> feat: Add commitlint to lint commit messages

.github/CONTRIBUTING.md
There was an erroneous info in the PR section: Travis CI don't check for **[skip ci]** at the PR level but rather at the commit level.
To fix that, add a new section about skipping building process.
=> docs: Add section about skipping building process

README.md
Adds text information on how to set up the Initial Data property to the respective section in the readme.
[skip ci]
=> docs: Add description to the Initial Data section

.eslintrc.js, README.md, __tests__/Form.spec.tsx, __tests__/Scope.spec.tsx, __tests__/components/Input.spec.tsx, __tests__/components/Select.spec.tsx, __tests__/utils/CustomInputClear.tsx, __tests__/utils/CustomInputParse.tsx, commitlint.config.js, example/src/App.tsx, example/src/components/DatePicker.tsx, example/src/components/ReactSelect.tsx, example/src/index.tsx, jest.config.js, lib/Context.tsx, lib/Form.tsx, lib/Scope.tsx, lib/components/Input.tsx, lib/components/Select.tsx, lib/index.ts, lib/useField.ts, rollup.config.js
Remove Prettier recommended rules from ESLint.
Prettier recommended settings were overriding some of AirBnB style guide rules.
Example: AirBnB points that quotes must be single, and with Prettier recommended rules we are using double quotes.
=> chore: Fix prettier integration

__tests__/components/Textarea.spec.tsx, lib/components/Input.tsx, lib/components/Textarea.tsx, lib/index.ts
`<Textarea />` was removed in #60, but it was all of a sudden. This PR restores the component but internally it renders a `<Input multiline />` which is the new way of doing it.
It also puts up a `console.warn` for the user to know that `<Textarea />` component will be deprecated in a future version of Unform.
Closes #74 
=> chore: Restore textarea component

.prettierrc, lib/Form.tsx, package.json
Tests and example files were not being linted by lint-staged.
Now lint-staged run over tests and example folders.
Fix prettier integration issues where in some cases trailing comma and single quotes were not being used.
Closes #78.
=> chore: Run lint-staged on tests and example

README.md, __tests__/components/FileInput.spec.tsx, example/src/App.tsx, lib/components/FileInput.tsx, lib/index.ts
Send files easily by adding new fields of type `FileInput`.
With the `FileInput` component you can also retrieve the progress of the upload when it is loaded into memory. This can be useful for blocking some buttons while the process is not complete preventing incomplete file data from being sent.
Example:
```jsx
<FileInput name="attach" onStartProgress={(progress) => console.log(progress)} />
```
=> feat: Add file input support

__tests__/Form.spec.tsx, __tests__/components/Select.spec.tsx, example/src/App.tsx, lib/components/Select.tsx
Currently, the `Select` component always display an option with the `Selecione...` text. This PR treats this *predefined text* as `placeholder` of the `Select` component.
___
**before**
```javascript
<Select
name="theme"
options={[
{ id: "dracula", title: "Dracula" },
{ id: "material", title: "Material" },
{ id: "shades-of-purple", title: "Shades of Purple" }
]}
/>
// will render
<select name="theme">
// default and no customizable placeholder below
<option value="">Selecione...</option>
<option value="dracula">Dracula</option>
<option value="shades-of-purple">Shades of Purple</option>
</select>
```
___
**after**
1. With placeholder prop:
```javascript
<Select
name="theme"
placeholder="Select a theme..." // <- 1. new prop goes here
options={[
{ id: "dracula", title: "Dracula" },
{ id: …
```
=> chore: Make select placeholder optional

lib/Form.tsx
Make `setFields` consider the state queue when running `unregisterField`
Without this fix, when you would cause a field to be unmounted, the whole `fields` stack would be lost, causing Unform to lose reference to all its fields. Now, because we're actually passing an arrow function, react will run our code inside the update queue, which should resolve the issue.
=> fix: Consider context inside unregisterField

README.md, __tests__/components/Check.spec.tsx, __tests__/components/Choice.spec.tsx, __tests__/utils/CustomInputParse.tsx, example/src/App.tsx, example/src/components/ReactSelect.tsx, lib/Form.tsx, lib/components/Check.tsx, lib/components/Choice.tsx, lib/index.ts, lib/types.ts
This resolves some aspects discussed in #20 and #66
This PR provides two new components:
* Check - for single options rendered as a single checkbox 
* Choice - for multiple options rendered as checkboxes or radio buttons
For Check component, the value returned will be _true_ or _false_.
For Choice component, if checkboxes (_multiple_ property) array of values will be returned, if radio buttons, only one string will be returned.
To made this possible, parseValue method was changed to receive the component ref instead of value.
```html
<Check name="fieldName" label="Test Field" />
```
will render
```html
<input type="checkbox" id="fieldName" name="fieldName" />
<label for="fieldName">TestField</label>
```
and when form is submitted, you will …
=> feat: Add Check and Choice components

README.md, __tests__/Form.spec.tsx, lib/Form.tsx
The resetForm helper function can now receive an optional object that updates the form data, if no value is provided the fields are cleared by default.
Close #67.
=> feat: Allow setting data on resetForm

docs/src/docs/guides/reset-form.mdx
In the documentation, in "Reset form", you end up resetting a single input using:
`formRef.current.clearValue('email');`
However, this does not seem to work anymore, to reset a single input, you must use **clearField**, like this:
`formRef.current.clearField('email');`
I just fixed that in the documentation.
These are the values that I have inside a **formRef.current**, look that there is no **clearValue**, but **clearField**.
=> docs: Replacing clearValue with clearField

docs/config/sidebar.yml, docs/src/docs/guides/basic-form.mdx, docs/src/docs/recipes/accessing-form-event.mdx, docs/src/docs/recipes/clear-input-error-on-focus.mdx, packages/core/__tests__/Form.spec.tsx, packages/core/__tests__/components/Input.tsx, packages/core/__tests__/components/ObjectInput.tsx, packages/core/__tests__/utils/CustomInputParse.tsx, packages/core/lib/Form.tsx, packages/core/lib/types.ts, packages/core/lib/useField.ts, packages/mobile/__tests__/Form.spec.tsx, packages/mobile/__tests__/components/Input.tsx
Did some changes to Unform due to some issues in the past weeks.
If we were using TypeScript and Unform, there was no easy way to set the value type, but now we can do:
```ts
registerField<Date>({
name: fieldName,
ref: inputRef.current,
setValue(ref, value) {
// value will automatically have Date type
},
getValue(ref) {
// typing error, should return a Date
return 'test'; 
}
})
```
Now, if an input has the `getValue` property in `registerField`, we won't need to pass `path` property anymore:
```js
registerField({
name: fieldName,
ref: inputRef.current,
getValue(ref) {
// return value manually
return inputRef.current.value; 
}
})
```
```js
registerField({
name: fieldName,
ref: inputRef.current,
path: 'value'
})
```
Changed fields variable to a ref instead of a state inside unform, so we …
=> Fix errors and improve API

packages/core/lib/useField.ts
As ``useField`` hook makes a lot of operations based on the ``name`` value, we must provide validation for it as well a descriptive error message.
I added the following error message: 
Refer to issue #248
=> Add name validation in useField

docs/src/docs/guides/reset-form.mdx
Parameter part had a typo
Change `paremeter` for `parameter`
=> docs: Fix typo in guides/reset-form.mdx 
